export { default as Code } from './code.js'
export { default as Heading } from './heading.js'
export { default as List } from './list'
export { default as P } from './p.js'
export { default as SmallCaps } from './smallcaps.js'
