/* eslint-disable @typescript-eslint/restrict-template-expressions */
const { deprecationMap } = require('./deprecationMap.js')

function getDeprecatedImports() {
  return `
  import { deprecationWarning } from '@pluralsight/ps-design-system-util'
  `
}

function getImports(baseImport, deprecated = false) {
  return `
  import React, { forwardRef } from 'react'
  ${deprecated && getDeprecatedImports()}
  import Icon, { IconComponent } from '${baseImport}'
  `
}

function getDeprecationHook(name) {
  const DEP_MESSAGE =
    'has been deprecated and will be removed in the future. Please use the new icon: '
  const warning = `${name} ${DEP_MESSAGE} ${deprecationMap[name]}`

  return `
    useEffect(() => {
      deprecationWarning(${warning})
    }, [])
  `
}

function getComponentBlock(name, svgString, deprecated = false) {
  const regex = />/

  return `
  const ${name} = forwardRef((props, ref) => {
    const { 'aria-label': ariaLabel, ...rest } = props

    ${deprecated && getDeprecationHook()}

    return (
      <Icon {...rest} ref={ref}>
        ${svgString.replace(
          regex,
          "role='img' {...(ariaLabel && { 'aria-label': ariaLabel })}>"
        )}
      </Icon>
    )
  }) as IconComponent
  `
}

function getComponentTemplate(baseImport, fileName, svgString) {
  const componentName = fileName.split('_')[0]
  const isDeprecated = fileName.includes('DEPRECATED')

  return `
  // This file is generated by running "icons" bin script.
  // Manual changes might be lost - proceed with caution!

  ${getImports(baseImport, isDeprecated)}

  ${getComponentBlock(componentName, svgString, isDeprecated)}

  ${componentName}.displayName = "${componentName}"
  ${componentName}.colors = Icon.colors
  ${componentName}.sizes = Icon.sizes

  export { ${componentName}  }
  `
}

module.exports = {
  getComponentTemplate
}
