// flow-typed signature: f23fc9ce90ab9b2280f67ccbf06b3679
// flow-typed version: <<STUB>>/github_v11/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'github' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'github/lib/error' {
  declare module.exports: any;
}

declare module 'github/lib/generate' {
  declare module.exports: any;
}

declare module 'github/lib/generateFlowTypes' {
  declare module.exports: any;
}

declare module 'github/lib/generateTypes' {
  declare module.exports: any;
}

declare module 'github/lib/generateTypeScriptTypes' {
  declare module.exports: any;
}

declare module 'github/lib/index' {
  declare module.exports: any;
}

declare module 'github/lib/promise' {
  declare module.exports: any;
}

declare module 'github/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'github/lib/error.js' {
  declare module.exports: $Exports<'github/lib/error'>;
}
declare module 'github/lib/generate.js' {
  declare module.exports: $Exports<'github/lib/generate'>;
}
declare module 'github/lib/generateFlowTypes.js' {
  declare module.exports: $Exports<'github/lib/generateFlowTypes'>;
}
declare module 'github/lib/generateTypes.js' {
  declare module.exports: $Exports<'github/lib/generateTypes'>;
}
declare module 'github/lib/generateTypeScriptTypes.js' {
  declare module.exports: $Exports<'github/lib/generateTypeScriptTypes'>;
}
declare module 'github/lib/index.js' {
  declare module.exports: $Exports<'github/lib/index'>;
}
declare module 'github/lib/promise.js' {
  declare module.exports: $Exports<'github/lib/promise'>;
}
declare module 'github/lib/util.js' {
  declare module.exports: $Exports<'github/lib/util'>;
}
