// flow-typed signature: c68518921d3ec7116cdbfeda301ec5e7
// flow-typed version: <<STUB>>/node-schedule_v1.2.5/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-schedule'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-schedule' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-schedule/lib/schedule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-schedule/lib/schedule.js' {
  declare module.exports: $Exports<'node-schedule/lib/schedule'>;
}
