// flow-typed signature: dd71709ca448b0f10030f85e7e53a694
// flow-typed version: <<STUB>>/semver-truncate_v1.1.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver-truncate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semver-truncate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'semver-truncate/index' {
  declare module.exports: $Exports<'semver-truncate'>;
}
declare module 'semver-truncate/index.js' {
  declare module.exports: $Exports<'semver-truncate'>;
}
