export { default as ForbiddenErrorPage } from './forbidden-error-page'
export { default as NotFoundErrorPage } from './not-found-error-page'
export { default as InternalServerErrorPage } from './internal-server-error-page'
export { default as ServiceUnavailableErrorPage } from './service-unavailable-error-page'
export { default as ErrorPage } from './error-page'
