on:
  push:
    paths:
      - 'docs/**'
    branches:
      - master

jobs:
  gh-release:
    runs-on: ubuntu-latest
    name: 🚀 Release to GitHub Pages
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2.2.1
        with:
          access-token: ${{ secrets.GH_PAGES_TOKEN }}
          deploy-branch: gh-pages
          git-config-name: gh-bot
          working-dir: docs
