on:
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: 🧪 Run unit tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
      # TODO: Uncomment after moving to Yarn 2, Yarn 1 does not cache deps
      # correctly, resulting in failing GH Action due to dep management
      # - run: yarn install
      # - run: yarn test:ci
